logging:
  level:
    org:
      springframework:
        r2dbc: debug

server:
  port: 8081

security:
  session:
    enabled: true
  jwt:
    access-token-ttl: 1h
    refresh-token-ttl: 48h
  rsa-public-key-spec:
    modulus: 22808357293297466386441814812365595554369148223814258949108094845049935021335040234837010071311963729014146367647617089996122581645283986091937373039194818573931965635835838355080901210759556858833153090470978004431137237337119068837093220909504034705582103206789036783330791536737124326373265439766885662466618030069766893693273535221432774817415437932550097470508807700265032718328911214694927075350456969387135914612867612686092047601869320356390225696898078737744435705443741647812672874904595825532635227554033124562342908835025714647780642630860827622169888430943574066638326669454004972234033274074211800775527
    exponent: 65537
